name: Cron Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API Route Product
        run: curl -X GET "https://pitchtiktok.vercel.app/api/cron/product"

      - name: Call Vercel API Route Sales
        run: curl -X GET "https://pitchtiktok.vercel.app/api/cron/sales"
