name: Cron Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API Route ROOM
        run: curl -X GET "https://pitchtiktok.vercel.app/api/cron/room"

      - name: Wait 5 seconds (Jaga-jaga data room selesai)
        run: sleep 5

      - name: Call Vercel API Route PRODUCT
        run: curl -X GET "https://pitchtiktok.vercel.app/api/cron/product"

      - name: Wait 5 seconds
        run: sleep 5

      - name: Call Vercel API Route SALES
        run: curl -X GET "https://pitchtiktok.vercel.app/api/cron/sales"
